export interface Job {
  id: string;
  title: string;
  role: string;
  location: string;
  compensation: string;
  about: string;
  responsibilities: string[];
  requirements: string[];
  applyUrl: string;
  status: 'open' | 'closed';
  slug?: string;
  deadline?: string;
}

export const jobs: Job[] = [
  {
    id: "sales-growth-specialist",
    title: "Sales & Growth Specialist",
    role: "Sales & Growth Specialist",
    location: "Remote / Global",
    compensation: "100,000 NGN Base Salary (Subject to monthly target) + 10% Commission on every paid gig (Min N300k monthly pay)",
    about: "We are looking for a results-driven Sales & Growth Specialist to actively source and secure high-ticket website development projects globally. You will be responsible for the entire lead generation and engagement cycle until the project is closed and a deposit is made.",
    responsibilities: [
      "Active Sourcing: Use any effective method (Cold Outreach, LinkedIn, TikTok, Email, etc.) to find clients needing WordPress, Shopify, GHL, or Custom Coding solutions.",
      "Lead Engagement: Initiate and maintain professional conversations, pitching our 'Precision Engineering' and 'Quality First' values.",
      "Brand Representation: Communicate our 4-step process—Talk, Build, Check, Launch—to build client trust.",
      "Trust Building: Educate leads on our secure payment processes, including Escrow options for international clients.",
      "Smooth Handover: Relinquish the lead to the engineering team once the upfront deposit is confirmed."
    ],
    requirements: [
      "Proven experience in sales or lead generation for technical services.",
      "Excellent communication skills in simple, professional English.",
      "Ability to work independently and meet monthly sales targets.",
      "Familiarity with platforms like Shopify, WordPress, and GHL is a plus."
    ],
    applyUrl: "https://calendly.com/cortdevs/sales-officer",
    status: "open"
  },
  {
    id: "operations-admin-officer",
    title: "Operations & Admin Officer",
    role: "Operations & Admin Officer",
    location: "Remote",
    compensation: "100,000 NGN Base Salary + 2% Commission on every successfully completed project.",
    about: "We are seeking a highly organized and authoritative Operations Officer to oversee the day-to-day activities of the company. You will be responsible for managing the flow of projects—from the moment a lead is generated by the marketing team to the final launch by the developers. Your goal is to ensure 'Quality Above All' and 100% customer satisfaction.",
    responsibilities: [
      "Team Management: Recruit, onboard, and monitor the performance of the marketing team and developers.",
      "Lead Oversight: Track the conversion process, ensuring marketers are pitching our 'Quality Over Cost' value properly.",
      "Project Lifecycle Management: Oversee the 4-step process: Discovery, Engineering, Quality Control, and Support.",
      "Quality Assurance: Ensure every project undergoes our 3 Rounds of Perfection (3 reviews) before final delivery.",
      "Operational Flow: Manage personnel, resolve internal conflicts, and ensure all digital assets are delivered on time with no excuses.",
      "Financial Tracking: Monitor project payments and ensure secure transactions via Escrow where necessary."
    ],
    requirements: [
      "Strong background in project management (Agile preferred).",
      "Experience managing remote teams and sales pipelines.",
      "Excellent command of professional English and brand communication.",
      "Ability to enforce strict technical standards and deadlines."
    ],
    applyUrl: "#",
    status: "closed"
  }
];
